// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AGrid: typeof import('./../src/components/grid/autogrid/AGrid.vue')['default']
    Alert: typeof import('./../src/components/alert/Alert.vue')['default']
    Area: typeof import('./../src/components/grid/area/Area.vue')['default']
    Badge: typeof import('./../src/components/badge/Badge.vue')['default']
    Button: typeof import('./../src/components/button/Button.vue')['default']
    ComponentDoc: typeof import('./src/components/layout/ComponentDoc.vue')['default']
    ConfigPanel: typeof import('./src/components/ConfigPanel.vue')['default']
    DynamicLinker: typeof import('./src/components/DynamicLinker.vue')['default']
    EmitDoc: typeof import('./src/components/apiDisplay/EmitDoc.vue')['default']
    ExamplePanel: typeof import('./src/components/ExamplePanel.vue')['default']
    File: typeof import('./../src/components/inputs/file/File.vue')['default']
    HeadPanel: typeof import('./src/components/HeadPanel.vue')['default']
    Checkbox: typeof import('./../src/components/inputs/checkbox/Checkbox.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    InputField: typeof import('./../src/components/inputs/inputField/InputField.vue')['default']
    List: typeof import('./../src/components/list/List.vue')['default']
    ListItem: typeof import('./../src/components/listitem/ListItem.vue')['default']
    Meter: typeof import('./../src/components/meter/Meter.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    Notification: typeof import('./../src/components/notification/Notification.vue')['default']
    PropDoc: typeof import('./src/components/apiDisplay/PropDoc.vue')['default']
    Radio: typeof import('./../src/components/inputs/radio/Radio.vue')['default']
    RadioGroup: typeof import('./../src/components/inputs/radioGroup/RadioGroup.vue')['default']
    RangeSlider: typeof import('./../src/components/inputs/rangeSlider/RangeSlider.vue')['default']
    Root: typeof import('./../src/components/root/Root.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    Slider: typeof import('./../src/components/inputs/slider/Slider.vue')['default']
    SlotDoc: typeof import('./src/components/apiDisplay/SlotDoc.vue')['default']
    TextArea: typeof import('./../src/components/inputs/textArea/TextArea.vue')['default']
  }
}

export {}
